Repository googleapis/nodejs-paginator, pull requests merged in 2019-03, with the labels that each got.

#96 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#98 build: fix types for sinon
  .gitignore
  src/index.ts
  test/index.ts
Labels: cla: yes

#97 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#99 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#91 feat: handle promise based functions
  src/index.ts
  test/index.ts
Labels: :rotating_light:, cla: yes

#101 refactor(ts): create generic for object streams
  src/index.ts
Labels: cla: yes

#102 Release @google-cloud/paginator v0.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#103 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#105 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes
