Repository googleapis/nodejs-paginator, pull requests merged in 2020-09, with the labels that each got.

#241 fix: add configs by running synthtool
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  synth.metadata
Labels: cla: yes

#237 chore(node): fix kokoro build path for cloud-rad
  synth.metadata
Labels: cla: yes, context: full

#243 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#245 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full
